baseURL: "https://oskarkramarz.github.io/"
title: Oskar Kramarz
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: 

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # To enable google analytics, opengraph, twitter-cards and schema.
  title: Oskar Kramarz
  # description: ""
  keywords: [Blog]
  author: Me
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShowNewsletterForm: true

  assets:
    # disableHLJS: true # To disable highlight.js
    # disableFingerprinting: true
    favicon: "/oskarkramarz-logo.png"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Oskar Kramarz"
    icon: /oskarkramarz-logo.png
    iconHeight: 28

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Oskar \U0001F44B"
    Content: No-code & low-code enthusiast, automation addict, indie hacker, entrepreneur.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/oskarkramarz"
    - name: linkedin
      url: "https://www.linkedin.com/in/oskarkramarz/"
    - name: ycombinator
      url: "https://news.ycombinator.com/user?id=oskarkramarz"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
    # URL: "https://github.com/<path_to_repo>/content"
    # Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  params:
    fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: search 
      name: Search
      url: /search/
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

permalinks:
  posts: /:title/

outputs:
  home:
    - HTML
    - RSS
    - JSON # Is necessary